import type { Product } from "./cart-store"

export const categories = [
  "Laptops",
  "Desktops", 
  "Networking",
  "Monitors",
  "Accessories",
  "Security",
  "Software",
  "Printers",
  "Storage",
] as const

export type Category = typeof categories[number]

export const brands = ["Dell", "HP", "Lenovo", "Cisco", "Ubiquiti", "Logitech", "Hikvision", "Microsoft", "Adobe", "Samsung", "Seagate", "Western Digital", "Canon", "Epson"] as const

export const products: Product[] = [
  // Laptops
  {
    id: "laptop-001",
    name: "Dell Latitude 5540",
    description: "15.6\" FHD, Intel Core i7-1355U, 16GB RAM, 512GB SSD, Windows 11 Pro. Built for business with enterprise security features and all-day battery life.",
    price: 1599,
    originalPrice: 1799,
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=500",
    category: "Laptops",
    brand: "Dell",
    inStock: true,
    featured: true,
    specs: {
      Processor: "Intel Core i7-1355U",
      RAM: "16GB DDR5",
      Storage: "512GB NVMe SSD",
      Display: "15.6\" FHD IPS",
      OS: "Windows 11 Pro",
    },
  },
  {
    id: "laptop-002",
    name: "HP EliteBook 840 G10",
    description: "14\" FHD, Intel Core i5-1345U, 16GB RAM, 256GB SSD, Windows 11 Pro. Sleek design with HP Wolf Security and Sure View privacy screen.",
    price: 1299,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500",
    category: "Laptops",
    brand: "HP",
    inStock: true,
    specs: {
      Processor: "Intel Core i5-1345U",
      RAM: "16GB DDR5",
      Storage: "256GB NVMe SSD",
      Display: "14\" FHD IPS",
      OS: "Windows 11 Pro",
    },
  },
  {
    id: "laptop-003",
    name: "Lenovo ThinkPad T14s Gen 4",
    description: "14\" 2.8K OLED, AMD Ryzen 7 PRO 7840U, 32GB RAM, 1TB SSD. Ultra-thin design with legendary ThinkPad durability.",
    price: 1899,
    originalPrice: 2199,
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500",
    category: "Laptops",
    brand: "Lenovo",
    inStock: true,
    featured: true,
    specs: {
      Processor: "AMD Ryzen 7 PRO 7840U",
      RAM: "32GB DDR5",
      Storage: "1TB NVMe SSD",
      Display: "14\" 2.8K OLED",
      OS: "Windows 11 Pro",
    },
  },
  {
    id: "laptop-004",
    name: "Dell XPS 15",
    description: "15.6\" 3.5K OLED, Intel Core i9-13900H, 32GB RAM, 1TB SSD. Premium ultrabook for creators and professionals.",
    price: 2499,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500",
    category: "Laptops",
    brand: "Dell",
    inStock: true,
    featured: true,
    specs: {
      Processor: "Intel Core i9-13900H",
      RAM: "32GB DDR5",
      Storage: "1TB NVMe SSD",
      Display: "15.6\" 3.5K OLED",
      OS: "Windows 11 Pro",
    },
  },
  {
    id: "laptop-005",
    name: "HP ProBook 450 G10",
    description: "15.6\" FHD, Intel Core i5-1335U, 8GB RAM, 256GB SSD. Budget-friendly business laptop.",
    price: 799,
    image: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=500",
    category: "Laptops",
    brand: "HP",
    inStock: true,
    specs: {
      Processor: "Intel Core i5-1335U",
      RAM: "8GB DDR4",
      Storage: "256GB NVMe SSD",
      Display: "15.6\" FHD",
      OS: "Windows 11 Pro",
    },
  },
  {
    id: "laptop-006",
    name: "Lenovo IdeaPad Slim 3",
    description: "15.6\" FHD, AMD Ryzen 5 7520U, 8GB RAM, 512GB SSD. Everyday laptop for home and office.",
    price: 549,
    originalPrice: 649,
    image: "https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=500",
    category: "Laptops",
    brand: "Lenovo",
    inStock: true,
    specs: {
      Processor: "AMD Ryzen 5 7520U",
      RAM: "8GB DDR5",
      Storage: "512GB NVMe SSD",
      Display: "15.6\" FHD IPS",
      OS: "Windows 11 Home",
    },
  },
  // Desktops
  {
    id: "desktop-001",
    name: "Dell OptiPlex 7010 SFF",
    description: "Intel Core i7-13700, 16GB RAM, 512GB SSD, Windows 11 Pro. Compact form factor for modern workspaces.",
    price: 1199,
    image: "https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=500",
    category: "Desktops",
    brand: "Dell",
    inStock: true,
    featured: true,
    specs: {
      Processor: "Intel Core i7-13700",
      RAM: "16GB DDR5",
      Storage: "512GB NVMe SSD",
      "Form Factor": "Small Form Factor",
      OS: "Windows 11 Pro",
    },
  },
  {
    id: "desktop-002",
    name: "HP EliteDesk 805 G9",
    description: "AMD Ryzen 7 PRO 5845, 16GB RAM, 512GB SSD. Powerful desktop with AMD reliability.",
    price: 1099,
    image: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=500",
    category: "Desktops",
    brand: "HP",
    inStock: true,
    specs: {
      Processor: "AMD Ryzen 7 PRO 5845",
      RAM: "16GB DDR5",
      Storage: "512GB NVMe SSD",
      "Form Factor": "Desktop Mini",
      OS: "Windows 11 Pro",
    },
  },
  {
    id: "desktop-003",
    name: "Lenovo ThinkCentre M70q Gen 4",
    description: "Intel Core i5-13400T, 8GB RAM, 256GB SSD. Ultra-compact desktop for space-constrained environments.",
    price: 749,
    image: "https://images.unsplash.com/photo-1591370874773-6702e8f12fd8?w=500",
    category: "Desktops",
    brand: "Lenovo",
    inStock: true,
    specs: {
      Processor: "Intel Core i5-13400T",
      RAM: "8GB DDR4",
      Storage: "256GB NVMe SSD",
      "Form Factor": "Tiny",
      OS: "Windows 11 Pro",
    },
  },
  // Networking
  {
    id: "network-001",
    name: "Cisco Catalyst 1000-24P",
    description: "24-Port Gigabit PoE+ Switch with 4x 1G SFP uplinks. Enterprise-grade switching with full PoE support.",
    price: 1899,
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500",
    category: "Networking",
    brand: "Cisco",
    inStock: true,
    featured: true,
    specs: {
      Ports: "24x 1GbE PoE+",
      Uplinks: "4x 1G SFP",
      "PoE Budget": "195W",
      "Switching Capacity": "56 Gbps",
      Management: "Web UI, CLI, SNMP",
    },
  },
  {
    id: "network-002",
    name: "Ubiquiti UniFi U6-Pro",
    description: "WiFi 6 Access Point, 4x4 MU-MIMO, 300+ devices. High-capacity AP for demanding environments.",
    price: 199,
    originalPrice: 249,
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=500",
    category: "Networking",
    brand: "Ubiquiti",
    inStock: true,
    specs: {
      WiFi: "WiFi 6 (802.11ax)",
      Speed: "Up to 4.8 Gbps",
      MIMO: "4x4 MU-MIMO",
      Coverage: "Up to 300+ clients",
      PoE: "PoE+ (802.3at)",
    },
  },
  {
    id: "network-003",
    name: "Cisco Meraki MR46",
    description: "Cloud-managed WiFi 6 access point with built-in security and analytics.",
    price: 899,
    image: "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=500",
    category: "Networking",
    brand: "Cisco",
    inStock: true,
    specs: {
      WiFi: "WiFi 6 (802.11ax)",
      Speed: "Up to 3.5 Gbps",
      Management: "Meraki Cloud",
      Security: "Built-in IDS/IPS",
      Coverage: "Up to 250 clients",
    },
  },
  {
    id: "network-004",
    name: "Ubiquiti UniFi Dream Machine Pro",
    description: "All-in-one network controller, security gateway, and NVR with 3.5\" HDD bay.",
    price: 499,
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500",
    category: "Networking",
    brand: "Ubiquiti",
    inStock: true,
    featured: true,
    specs: {
      Processor: "1.7 GHz Quad-Core",
      RAM: "4GB",
      Ports: "8x 1GbE, 1x 10G SFP+",
      Storage: "3.5\" HDD Bay for NVR",
      Features: "Controller, Gateway, NVR",
    },
  },
  {
    id: "network-005",
    name: "TP-Link TL-SG1016PE",
    description: "16-Port Gigabit PoE+ Switch. Budget-friendly PoE switch for small businesses.",
    price: 249,
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500",
    category: "Networking",
    brand: "TP-Link",
    inStock: true,
    specs: {
      Ports: "16x 1GbE (8 PoE+)",
      "PoE Budget": "110W",
      "Switching Capacity": "32 Gbps",
      Management: "Unmanaged",
    },
  },
  // Monitors
  {
    id: "monitor-001",
    name: "Dell UltraSharp U2723QE",
    description: "27\" 4K USB-C Hub Monitor with IPS Black technology and 98% DCI-P3 color accuracy.",
    price: 799,
    originalPrice: 899,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500",
    category: "Monitors",
    brand: "Dell",
    inStock: true,
    featured: true,
    specs: {
      "Screen Size": "27\"",
      Resolution: "4K UHD (3840x2160)",
      Panel: "IPS Black",
      "Color Accuracy": "98% DCI-P3",
      Connectivity: "USB-C 90W, HDMI, DP",
    },
  },
  {
    id: "monitor-002",
    name: "HP E27m G4",
    description: "27\" QHD Conferencing Monitor with built-in webcam, speakers, and noise-canceling mic.",
    price: 549,
    image: "https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=500",
    category: "Monitors",
    brand: "HP",
    inStock: true,
    specs: {
      "Screen Size": "27\"",
      Resolution: "QHD (2560x1440)",
      Panel: "IPS",
      Webcam: "5MP with Windows Hello",
      Audio: "Speakers + Mic",
    },
  },
  {
    id: "monitor-003",
    name: "Samsung ViewFinity S8",
    description: "32\" 4K USB-C Monitor with HDR600 and Intelligent Eye Care.",
    price: 699,
    image: "https://images.unsplash.com/photo-1551645120-d70bfe84c826?w=500",
    category: "Monitors",
    brand: "Samsung",
    inStock: true,
    specs: {
      "Screen Size": "32\"",
      Resolution: "4K UHD (3840x2160)",
      Panel: "IPS",
      HDR: "HDR600",
      Connectivity: "USB-C 90W, HDMI 2.0",
    },
  },
  {
    id: "monitor-004",
    name: "Dell P2422H",
    description: "24\" FHD Professional Monitor with ComfortView Plus and USB Hub.",
    price: 279,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500",
    category: "Monitors",
    brand: "Dell",
    inStock: true,
    specs: {
      "Screen Size": "24\"",
      Resolution: "FHD (1920x1080)",
      Panel: "IPS",
      Features: "ComfortView Plus",
      Connectivity: "HDMI, DP, USB Hub",
    },
  },
  // Security
  {
    id: "security-001",
    name: "Hikvision DS-2CD2H86G2-IZS",
    description: "8MP AcuSense Varifocal Dome Camera with motorized 2.8-12mm lens. AI-powered motion detection.",
    price: 399,
    originalPrice: 499,
    image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=500",
    category: "Security",
    brand: "Hikvision",
    inStock: true,
    featured: true,
    specs: {
      Resolution: "8MP (4K)",
      Lens: "2.8-12mm Motorized",
      "Night Vision": "40m IR",
      Features: "AcuSense AI, WDR",
      Protection: "IP67, IK10",
    },
  },
  {
    id: "security-002",
    name: "Hikvision DS-7616NI-K2",
    description: "16-Channel 4K NVR with 2 SATA interfaces. Supports up to 8MP cameras.",
    price: 349,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500",
    category: "Security",
    brand: "Hikvision",
    inStock: true,
    specs: {
      Channels: "16",
      Resolution: "Up to 8MP",
      Storage: "2x SATA (up to 10TB each)",
      Bandwidth: "160 Mbps",
      Outputs: "HDMI, VGA",
    },
  },
  {
    id: "security-003",
    name: "Dahua DH-IPC-HFW2831S-S-S2",
    description: "8MP IR Bullet Camera with Smart Motion Detection. Starlight technology for low-light performance.",
    price: 299,
    image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=500",
    category: "Security",
    brand: "Dahua",
    inStock: true,
    specs: {
      Resolution: "8MP (4K)",
      Lens: "2.8mm Fixed",
      "Night Vision": "30m IR Starlight",
      Features: "SMD Plus, WDR",
      Protection: "IP67",
    },
  },
  {
    id: "security-004",
    name: "ZKTeco SpeedFace V5L",
    description: "Face Recognition & Palm Access Control Terminal with temperature detection.",
    price: 599,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500",
    category: "Security",
    brand: "ZKTeco",
    inStock: true,
    specs: {
      Recognition: "Face + Palm",
      Capacity: "6,000 Faces, 6,000 Palms",
      Screen: "5\" Touch",
      Features: "Temperature Detection",
      Interface: "TCP/IP, RS485",
    },
  },
  // Accessories
  {
    id: "accessory-001",
    name: "Logitech MX Master 3S",
    description: "Advanced wireless mouse with 8K DPI sensor and quiet clicks. Works on any surface including glass.",
    price: 99,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500",
    category: "Accessories",
    brand: "Logitech",
    inStock: true,
    specs: {
      DPI: "Up to 8000",
      Buttons: "7",
      Battery: "70 days",
      Connectivity: "Bluetooth + USB Receiver",
      Features: "MagSpeed scroll, Multi-device",
    },
  },
  {
    id: "accessory-002",
    name: "Logitech MX Keys S",
    description: "Advanced wireless keyboard with smart backlighting and programmable keys.",
    price: 119,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500",
    category: "Accessories",
    brand: "Logitech",
    inStock: true,
    specs: {
      Type: "Membrane",
      Layout: "Full-size",
      Backlight: "Smart illumination",
      Battery: "10 days (backlit), 5 months",
      Connectivity: "Bluetooth + USB Receiver",
    },
  },
  {
    id: "accessory-003",
    name: "Dell WD19TBS Thunderbolt Dock",
    description: "Thunderbolt 4 docking station with 130W power delivery. Connect up to 3 displays.",
    price: 399,
    originalPrice: 449,
    image: "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=500",
    category: "Accessories",
    brand: "Dell",
    inStock: true,
    featured: true,
    specs: {
      Interface: "Thunderbolt 4",
      "Power Delivery": "130W",
      "Display Support": "Up to 3 x 4K",
      Ports: "USB-C, USB-A, HDMI, DP, Ethernet",
      Features: "Daisy chain support",
    },
  },
  {
    id: "accessory-004",
    name: "Logitech C920s Pro HD",
    description: "HD webcam with privacy shutter and automatic light correction.",
    price: 79,
    image: "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=500",
    category: "Accessories",
    brand: "Logitech",
    inStock: true,
    specs: {
      Resolution: "1080p @ 30fps",
      "Field of View": "78°",
      Features: "Autofocus, Privacy Shutter",
      Microphone: "Stereo",
      Connectivity: "USB-A",
    },
  },
  // Software
  {
    id: "software-001",
    name: "Microsoft 365 Business Standard",
    description: "Complete productivity suite including Word, Excel, PowerPoint, Teams, and 1TB OneDrive.",
    price: 150,
    image: "https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=500",
    category: "Software",
    brand: "Microsoft",
    inStock: true,
    specs: {
      License: "1 User / Year",
      Apps: "Word, Excel, PowerPoint, Teams",
      Storage: "1TB OneDrive",
      Devices: "Up to 5 devices",
      Support: "Microsoft Support",
    },
  },
  {
    id: "software-002",
    name: "Adobe Creative Cloud Complete",
    description: "All Adobe apps including Photoshop, Illustrator, Premiere Pro, and more.",
    price: 660,
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=500",
    category: "Software",
    brand: "Adobe",
    inStock: true,
    featured: true,
    specs: {
      License: "1 User / Year",
      Apps: "20+ Creative Apps",
      Storage: "100GB Cloud",
      Features: "Adobe Fonts, Portfolio",
      Updates: "Always latest version",
    },
  },
  {
    id: "software-003",
    name: "Windows 11 Pro License",
    description: "Windows 11 Professional perpetual license. Includes BitLocker, Remote Desktop, and Hyper-V.",
    price: 199,
    image: "https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=500",
    category: "Software",
    brand: "Microsoft",
    inStock: true,
    specs: {
      License: "Perpetual",
      Edition: "Professional",
      Features: "BitLocker, Hyper-V, RDP",
      Updates: "Security updates included",
      Activation: "Digital license",
    },
  },
  {
    id: "software-004",
    name: "Kaspersky Endpoint Security",
    description: "Enterprise endpoint protection with EDR capabilities. Per device, per year.",
    price: 45,
    image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=500",
    category: "Software",
    brand: "Kaspersky",
    inStock: true,
    specs: {
      License: "1 Device / Year",
      Protection: "Antivirus, EDR",
      Features: "Encryption, Web Control",
      Management: "Kaspersky Security Center",
      Support: "24/7 Support",
    },
  },
  // Printers
  {
    id: "printer-001",
    name: "HP LaserJet Pro MFP M428fdw",
    description: "All-in-one mono laser printer with duplex printing, scanning, and fax.",
    price: 449,
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=500",
    category: "Printers",
    brand: "HP",
    inStock: true,
    specs: {
      Type: "Mono Laser MFP",
      "Print Speed": "40 ppm",
      Duplex: "Automatic",
      Functions: "Print, Scan, Copy, Fax",
      Connectivity: "USB, Ethernet, WiFi",
    },
  },
  {
    id: "printer-002",
    name: "Canon imageCLASS MF453dw",
    description: "Compact wireless mono laser printer for small workgroups.",
    price: 349,
    originalPrice: 399,
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=500",
    category: "Printers",
    brand: "Canon",
    inStock: true,
    specs: {
      Type: "Mono Laser MFP",
      "Print Speed": "40 ppm",
      Duplex: "Automatic",
      Functions: "Print, Scan, Copy",
      Connectivity: "USB, Ethernet, WiFi",
    },
  },
  {
    id: "printer-003",
    name: "Epson EcoTank L6290",
    description: "All-in-one ink tank printer with ultra-high page yields. Cost-effective printing.",
    price: 399,
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=500",
    category: "Printers",
    brand: "Epson",
    inStock: true,
    featured: true,
    specs: {
      Type: "Color Inkjet MFP",
      "Print Speed": "15.5 ipm Color",
      Duplex: "Automatic",
      Functions: "Print, Scan, Copy, Fax",
      Ink: "EcoTank (refillable)",
    },
  },
  // Storage
  {
    id: "storage-001",
    name: "Seagate IronWolf Pro 8TB",
    description: "NAS hard drive with AgileArray technology. Built for 24/7 operation in multi-bay NAS.",
    price: 249,
    image: "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=500",
    category: "Storage",
    brand: "Seagate",
    inStock: true,
    specs: {
      Capacity: "8TB",
      Interface: "SATA 6Gb/s",
      Speed: "7200 RPM",
      Cache: "256MB",
      Workload: "300TB/year",
    },
  },
  {
    id: "storage-002",
    name: "WD Red Plus 4TB",
    description: "NAS hard drive optimized for home and small business NAS systems.",
    price: 119,
    image: "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=500",
    category: "Storage",
    brand: "Western Digital",
    inStock: true,
    specs: {
      Capacity: "4TB",
      Interface: "SATA 6Gb/s",
      Speed: "5400 RPM (CMR)",
      Cache: "256MB",
      Workload: "180TB/year",
    },
  },
  {
    id: "storage-003",
    name: "Samsung 990 Pro 2TB NVMe",
    description: "PCIe 4.0 NVMe SSD with read speeds up to 7,450 MB/s. Perfect for workstations.",
    price: 189,
    originalPrice: 229,
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=500",
    category: "Storage",
    brand: "Samsung",
    inStock: true,
    featured: true,
    specs: {
      Capacity: "2TB",
      Interface: "PCIe 4.0 x4 NVMe",
      "Read Speed": "7,450 MB/s",
      "Write Speed": "6,900 MB/s",
      Endurance: "1,200 TBW",
    },
  },
  {
    id: "storage-004",
    name: "Synology DS923+ NAS",
    description: "4-bay NAS with AMD Ryzen CPU. Perfect for small business file storage and backup.",
    price: 649,
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500",
    category: "Storage",
    brand: "Synology",
    inStock: true,
    featured: true,
    specs: {
      Bays: "4 (expandable to 9)",
      Processor: "AMD Ryzen R1600",
      RAM: "4GB DDR4 (up to 32GB)",
      Network: "2x 1GbE",
      Features: "Docker, VMs, Surveillance",
    },
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => {
    const cat = typeof p.category === 'string' ? p.category : p.category?.name || ''
    return cat.toLowerCase() === category.toLowerCase()
  })
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured)
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase()
  return products.filter(
    (p) => {
      const cat = typeof p.category === 'string' ? p.category : p.category?.name || ''
      return p.name.toLowerCase().includes(lowerQuery) ||
        (p.description?.toLowerCase().includes(lowerQuery) ?? false) ||
        cat.toLowerCase().includes(lowerQuery) ||
        (p.brand?.toLowerCase().includes(lowerQuery) ?? false)
    }
  )
}
